CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CORREO VARCHAR2(50),
    CONTRASEÑA VARCHAR2(50),
    TELEFONO NUMBER(9),
    PUNTOS NUMBER(5)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(50),
    PUESTO VARCHAR(25),
    SALARIO NUMBER(4),
    TURNO VARCHAR2(10),
    FECHA_CONTRATACIÓN DATE
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CATEGORIA VARCHAR2(25),
    PRECIO NUMBER(4),
    STOCK NUMBER(4),
    ID_PROVEEDORES NUMBER(3)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    TELEFONO NUMBER(9),
    EMAIL VARCHAR2(50),
    DIRECCION VARCHAR2(50)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER(4),
    FECHA DATE,
    TOTAL NUMBER(5,2),
    ID_EMPLEADO NUMBER(3),
    ID_USUARIO NUMBER(3)
);

CREATE TABLE INVENTARIO (
    ID_MOVIMIENTO NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    CANTIDAD NUMBER(3),
    FECHA DATE
);