-- =========================
-- TABLA CLIENTES
-- =========================
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    TELEFONO VARCHAR(9),
    PUNTOS INT DEFAULT 0,
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- =========================
-- TABLA USUARIOS
-- =========================
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE,
    CONTRASENA VARCHAR(255),
    ROL ENUM('CLIENTE','TRABAJADOR'),
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- =========================
-- TABLA EMPLEADOS
-- =========================
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    PUESTO VARCHAR(25),
    SALARIO DECIMAL(6,2),
    TURNO VARCHAR(10),
    FECHA_CONTRATACION DATE,
    CONSTRAINT FK_EMPLEADO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- =========================
-- TABLA PROVEEDORES
-- =========================
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(9),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(50)
);

-- =========================
-- TABLA PRODUCTOS
-- =========================
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    CATEGORIA VARCHAR(25),
    PRECIO DECIMAL(6,2),
    STOCK INT(4),
    ID_PROVEEDOR INT(3),
    RUTA_IMAGEN VARCHAR(255),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

-- =========================
-- TABLA PEDIDOS
-- =========================
CREATE TABLE PEDIDOS (
    ID_PEDIDO INT(4) PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    TOTAL DECIMAL(6,2),
    ID_EMPLEADO INT(3),
    ID_CLIENTE INT(3),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

-- =========================
-- TABLA DETALLE_PEDIDO
-- =========================
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE INT(3) PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT(4),
    ID_PRODUCTO INT(3),
    CANTIDAD INT(3),
    PRECIO_UNITARIO DECIMAL(6,2),
    SUBTOTAL DECIMAL(6,2),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- =========================
-- TABLA INVENTARIO
-- =========================
CREATE TABLE INVENTARIO (
    ID_MOVIMIENTO INT(3) PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT(3),
    CANTIDAD INT(4),
    FECHA DATE,
    CONSTRAINT FK_PRODUCTO2 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- =========================
-- TABLA LOYALTY_TRANSACTIONS
-- =========================
CREATE TABLE LOYALTY_TRANSACTIONS (
    ID_TRANSACCION INT(5) PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT(3),
    ID_PEDIDO INT(4) NULL,
    TIPO ENUM('GANADO','GASTADO'),
    PUNTOS INT(5),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPCION VARCHAR(100),
    CONSTRAINT FK_CLIENTE_LOYALTY FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_PEDIDO_LOYALTY FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

-- =========================
-- TABLA RECOMPENSAS
-- =========================
CREATE TABLE RECOMPENSAS (
    ID_RECOMPENSA INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    DESCRIPCION VARCHAR(100),
    PUNTOS_REQUERIDOS INT(5)
);

-- =========================
-- TABLA CANJES
-- =========================
CREATE TABLE CANJES (
    ID_CANJE INT(4) PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT(3),
    ID_RECOMPENSA INT(3),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CLIENTE_CANJE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_RECOMPENSA FOREIGN KEY (ID_RECOMPENSA) REFERENCES RECOMPENSAS(ID_RECOMPENSA)
);

-- =========================
-- TABLA PAGOS
-- =========================
CREATE TABLE PAGOS (
    ID_PAGO INT(4) PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT(4),
    TIPO_PAGO ENUM('EFECTIVO', 'TARJETA', 'PAYPAL', 'BIZUM', 'OTRO'),
    MONTO DECIMAL(6,2),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PEDIDO_PAGO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);


-- =========================
-- TABLA ESPECIALIDAD
-- =========================
CREATE TABLE ESPECIALIDAD_ACTUAL (
    ID_ESPECIALIDAD INT PRIMARY KEY AUTO_INCREMENT,
    ORIGEN_GRANO VARCHAR(100),
    NOTAS_CATA VARCHAR(150),
    TUESTE VARCHAR(50),
    METODO_FILTRO VARCHAR(50),
    DESCRIPCION_FILTRO VARCHAR(200),
    SEASONAL_NOMBRE VARCHAR(100),
    SEASONAL_DESCRIPCION VARCHAR(200),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);