CREATE TABLE CLIENTES (
    ID_CLIENTE INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    CORREO VARCHAR(50),
    CONTRASENA VARCHAR(50),
    TELEFONO VARCHAR(9),
    PUNTOS INT(5)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    PUESTO VARCHAR(25),
    SALARIO DECIMAL(6,2),
    TURNO VARCHAR(10),
    FECHA_CONTRATACION DATE
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(9),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(50)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    CATEGORIA VARCHAR(25),
    PRECIO DECIMAL(6,2),
    STOCK INT(4),
    ID_PROVEEDOR INT(3),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT(4) PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    TOTAL DECIMAL(6,2),
    ID_EMPLEADO INT(3),
    ID_CLIENTE INT(3),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE INT(3) PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT(4),
    ID_PRODUCTO INT(3),
    CANTIDAD INT(3),
    PRECIO_UNITARIO DECIMAL(6,2),
    SUBTOTAL DECIMAL(6,2),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE INVENTARIO (
    ID_MOVIMIENTO INT(3) PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT(3),
    CANTIDAD INT(4),
    FECHA DATE,
    CONSTRAINT FK_PRODUCTO2 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PROMOCIONES (
    ID_PROMOCION INT(3) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    DESCRIPCION VARCHAR(100),
    ID_PRODUCTO INT(3),
    CONSTRAINT FK_PRODUCTO3 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);
